# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Tue Feb 28 18:59:26 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
  _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
  _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
  def setupUi(self, MainWindow):
    MainWindow.setObjectName(_fromUtf8("MainWindow"))
    MainWindow.resize(913, 592)
    self.centralwidget = QtGui.QWidget(MainWindow)
    self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
    self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
    self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
    self.label = QtGui.QLabel(self.centralwidget)
    self.label.setMinimumSize(QtCore.QSize(0, 100))
    self.label.setStyleSheet(_fromUtf8("QLabel {\n"
"  padding: 10px;\n"
"  font-size: 30px;\n"
"  background-color: rgb(103, 152, 203);\n"
"  color: white;\n"
"}"))
    self.label.setObjectName(_fromUtf8("label"))
    self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
    self.progressList = QInstallProgress(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.progressList.sizePolicy().hasHeightForWidth())
    self.progressList.setSizePolicy(sizePolicy)
    self.progressList.setMaximumSize(QtCore.QSize(140, 16777215))
    self.progressList.setStyleSheet(_fromUtf8(""))
    self.progressList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
    self.progressList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
    self.progressList.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
    self.progressList.setAutoExpandDelay(1)
    self.progressList.setIndentation(0)
    self.progressList.setItemsExpandable(False)
    self.progressList.setAnimated(True)
    self.progressList.setObjectName(_fromUtf8("progressList"))
    item_0 = QtGui.QTreeWidgetItem(self.progressList)
    item_0 = QtGui.QTreeWidgetItem(self.progressList)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    item_0 = QtGui.QTreeWidgetItem(self.progressList)
    item_0 = QtGui.QTreeWidgetItem(self.progressList)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    item_0 = QtGui.QTreeWidgetItem(self.progressList)
    item_0 = QtGui.QTreeWidgetItem(self.progressList)
    self.progressList.header().setVisible(False)
    self.gridLayout_2.addWidget(self.progressList, 1, 0, 1, 1)
    self.contentWidget = QtGui.QStackedWidget(self.centralwidget)
    self.contentWidget.setObjectName(_fromUtf8("contentWidget"))
    self.content1 = QtGui.QWidget()
    self.content1.setObjectName(_fromUtf8("content1"))
    self.gridLayout_3 = QtGui.QGridLayout(self.content1)
    self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
    self.frame_2 = QtGui.QFrame(self.content1)
    self.frame_2.setObjectName(_fromUtf8("frame_2"))
    self.gridLayout_5 = QtGui.QGridLayout(self.frame_2)
    self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
    self.label_2 = QtGui.QLabel(self.frame_2)
    self.label_2.setTextFormat(QtCore.Qt.RichText)
    self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
    self.label_2.setWordWrap(True)
    self.label_2.setObjectName(_fromUtf8("label_2"))
    self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
    self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1)
    self.contentWidget.addWidget(self.content1)
    self.content2 = QtGui.QWidget()
    self.content2.setObjectName(_fromUtf8("content2"))
    self.gridLayout_4 = QtGui.QGridLayout(self.content2)
    self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
    self.frame_3 = QtGui.QFrame(self.content2)
    self.frame_3.setObjectName(_fromUtf8("frame_3"))
    self.gridLayout_6 = QtGui.QGridLayout(self.frame_3)
    self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
    self.label_3 = QtGui.QLabel(self.frame_3)
    self.label_3.setTextFormat(QtCore.Qt.RichText)
    self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
    self.label_3.setWordWrap(True)
    self.label_3.setObjectName(_fromUtf8("label_3"))
    self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
    self.gridLayout_4.addWidget(self.frame_3, 0, 0, 1, 1)
    self.contentWidget.addWidget(self.content2)
    self.content3 = QtGui.QWidget()
    self.content3.setObjectName(_fromUtf8("content3"))
    self.gridLayout_8 = QtGui.QGridLayout(self.content3)
    self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
    self.frame_4 = QtGui.QFrame(self.content3)
    self.frame_4.setObjectName(_fromUtf8("frame_4"))
    self.gridLayout_7 = QtGui.QGridLayout(self.frame_4)
    self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
    self.verticalLayout = QtGui.QVBoxLayout()
    self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
    self.label_4 = QtGui.QLabel(self.frame_4)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
    self.label_4.setSizePolicy(sizePolicy)
    self.label_4.setTextFormat(QtCore.Qt.RichText)
    self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
    self.label_4.setWordWrap(True)
    self.label_4.setObjectName(_fromUtf8("label_4"))
    self.verticalLayout.addWidget(self.label_4)
    self.gridLayout_7.addLayout(self.verticalLayout, 0, 0, 1, 1)
    self.partitionList = QtGui.QTreeWidget(self.frame_4)
    self.partitionList.setIndentation(0)
    self.partitionList.setRootIsDecorated(False)
    self.partitionList.setItemsExpandable(False)
    self.partitionList.setAnimated(True)
    self.partitionList.setObjectName(_fromUtf8("partitionList"))
    self.partitionList.header().setCascadingSectionResizes(True)
    self.partitionList.header().setSortIndicatorShown(True)
    self.gridLayout_7.addWidget(self.partitionList, 1, 0, 1, 1)
    self.gridLayout_8.addWidget(self.frame_4, 0, 0, 1, 1)
    self.contentWidget.addWidget(self.content3)
    self.content4 = QtGui.QWidget()
    self.content4.setObjectName(_fromUtf8("content4"))
    self.gridLayout_12 = QtGui.QGridLayout(self.content4)
    self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
    self.frame_6 = QtGui.QFrame(self.content4)
    self.frame_6.setObjectName(_fromUtf8("frame_6"))
    self.gridLayout_11 = QtGui.QGridLayout(self.frame_6)
    self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
    self.verticalLayout_2 = QtGui.QVBoxLayout()
    self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
    self.label_6 = QtGui.QLabel(self.frame_6)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
    self.label_6.setSizePolicy(sizePolicy)
    self.label_6.setTextFormat(QtCore.Qt.RichText)
    self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
    self.label_6.setWordWrap(True)
    self.label_6.setObjectName(_fromUtf8("label_6"))
    self.verticalLayout_2.addWidget(self.label_6)
    self.gridLayout_11.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
    self.swapList = QtGui.QTreeWidget(self.frame_6)
    self.swapList.setIndentation(0)
    self.swapList.setRootIsDecorated(False)
    self.swapList.setItemsExpandable(False)
    self.swapList.setAnimated(True)
    self.swapList.setObjectName(_fromUtf8("swapList"))
    self.swapList.header().setCascadingSectionResizes(True)
    self.swapList.header().setSortIndicatorShown(True)
    self.gridLayout_11.addWidget(self.swapList, 1, 0, 1, 1)
    self.gridLayout_12.addWidget(self.frame_6, 0, 0, 1, 1)
    self.contentWidget.addWidget(self.content4)
    self.content5 = QtGui.QWidget()
    self.content5.setObjectName(_fromUtf8("content5"))
    self.gridLayout_9 = QtGui.QGridLayout(self.content5)
    self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
    self.frame_5 = QtGui.QFrame(self.content5)
    self.frame_5.setObjectName(_fromUtf8("frame_5"))
    self.gridLayout_10 = QtGui.QGridLayout(self.frame_5)
    self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
    self.diskSpaceWarning = QtGui.QLabel(self.frame_5)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.diskSpaceWarning.sizePolicy().hasHeightForWidth())
    self.diskSpaceWarning.setSizePolicy(sizePolicy)
    self.diskSpaceWarning.setTextFormat(QtCore.Qt.RichText)
    self.diskSpaceWarning.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
    self.diskSpaceWarning.setWordWrap(True)
    self.diskSpaceWarning.setObjectName(_fromUtf8("diskSpaceWarning"))
    self.gridLayout_10.addWidget(self.diskSpaceWarning, 0, 0, 1, 1)
    self.gridLayout_9.addWidget(self.frame_5, 0, 0, 1, 1)
    self.contentWidget.addWidget(self.content5)
    self.page = QtGui.QWidget()
    self.page.setObjectName(_fromUtf8("page"))
    self.gridLayout_13 = QtGui.QGridLayout(self.page)
    self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
    self.diskSpaceWarning_2 = QtGui.QLabel(self.page)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.diskSpaceWarning_2.sizePolicy().hasHeightForWidth())
    self.diskSpaceWarning_2.setSizePolicy(sizePolicy)
    self.diskSpaceWarning_2.setTextFormat(QtCore.Qt.RichText)
    self.diskSpaceWarning_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
    self.diskSpaceWarning_2.setWordWrap(True)
    self.diskSpaceWarning_2.setObjectName(_fromUtf8("diskSpaceWarning_2"))
    self.gridLayout_13.addWidget(self.diskSpaceWarning_2, 0, 0, 1, 1)
    self.contentWidget.addWidget(self.page)
    self.content6 = QtGui.QWidget()
    self.content6.setObjectName(_fromUtf8("content6"))
    self.gridLayout_14 = QtGui.QGridLayout(self.content6)
    self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
    self.frame_7 = QtGui.QFrame(self.content6)
    self.frame_7.setObjectName(_fromUtf8("frame_7"))
    self.formLayout_2 = QtGui.QFormLayout(self.frame_7)
    self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
    self.webBrowserLabel = QtGui.QLabel(self.frame_7)
    self.webBrowserLabel.setObjectName(_fromUtf8("webBrowserLabel"))
    self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.webBrowserLabel)
    self.webBrowserComboBox = QtGui.QComboBox(self.frame_7)
    self.webBrowserComboBox.setObjectName(_fromUtf8("webBrowserComboBox"))
    self.webBrowserComboBox.addItem(_fromUtf8(""))
    self.webBrowserComboBox.addItem(_fromUtf8(""))
    self.webBrowserComboBox.addItem(_fromUtf8(""))
    self.webBrowserComboBox.addItem(_fromUtf8(""))
    self.webBrowserComboBox.addItem(_fromUtf8(""))
    self.webBrowserComboBox.addItem(_fromUtf8(""))
    self.webBrowserComboBox.addItem(_fromUtf8(""))
    self.webBrowserComboBox.addItem(_fromUtf8(""))
    self.webBrowserComboBox.addItem(_fromUtf8(""))
    self.webBrowserComboBox.addItem(_fromUtf8(""))
    self.webBrowserComboBox.addItem(_fromUtf8(""))
    self.webBrowserComboBox.addItem(_fromUtf8(""))
    self.webBrowserComboBox.addItem(_fromUtf8(""))
    self.webBrowserComboBox.addItem(_fromUtf8(""))
    self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.webBrowserComboBox)
    self.mailClientLabel = QtGui.QLabel(self.frame_7)
    self.mailClientLabel.setObjectName(_fromUtf8("mailClientLabel"))
    self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.mailClientLabel)
    self.mailClientComboBox = QtGui.QComboBox(self.frame_7)
    self.mailClientComboBox.setObjectName(_fromUtf8("mailClientComboBox"))
    self.mailClientComboBox.addItem(_fromUtf8(""))
    self.mailClientComboBox.addItem(_fromUtf8(""))
    self.mailClientComboBox.addItem(_fromUtf8(""))
    self.mailClientComboBox.addItem(_fromUtf8(""))
    self.mailClientComboBox.addItem(_fromUtf8(""))
    self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.mailClientComboBox)
    self.bitTorrentClientLabel = QtGui.QLabel(self.frame_7)
    self.bitTorrentClientLabel.setObjectName(_fromUtf8("bitTorrentClientLabel"))
    self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.bitTorrentClientLabel)
    self.bitTorrentClientComboBox = QtGui.QComboBox(self.frame_7)
    self.bitTorrentClientComboBox.setObjectName(_fromUtf8("bitTorrentClientComboBox"))
    self.bitTorrentClientComboBox.addItem(_fromUtf8(""))
    self.bitTorrentClientComboBox.addItem(_fromUtf8(""))
    self.bitTorrentClientComboBox.addItem(_fromUtf8(""))
    self.bitTorrentClientComboBox.addItem(_fromUtf8(""))
    self.bitTorrentClientComboBox.addItem(_fromUtf8(""))
    self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.bitTorrentClientComboBox)
    self.chatClientLabel = QtGui.QLabel(self.frame_7)
    self.chatClientLabel.setObjectName(_fromUtf8("chatClientLabel"))
    self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.chatClientLabel)
    self.chatClientComboBox = QtGui.QComboBox(self.frame_7)
    self.chatClientComboBox.setObjectName(_fromUtf8("chatClientComboBox"))
    self.chatClientComboBox.addItem(_fromUtf8(""))
    self.chatClientComboBox.addItem(_fromUtf8(""))
    self.chatClientComboBox.addItem(_fromUtf8(""))
    self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.chatClientComboBox)
    self.gridLayout_14.addWidget(self.frame_7, 0, 0, 1, 1)
    self.contentWidget.addWidget(self.content6)
    self.page_2 = QtGui.QWidget()
    self.page_2.setObjectName(_fromUtf8("page_2"))
    self.gridLayout_15 = QtGui.QGridLayout(self.page_2)
    self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
    self.frame_8 = QtGui.QFrame(self.page_2)
    self.frame_8.setObjectName(_fromUtf8("frame_8"))
    self.formLayout = QtGui.QFormLayout(self.frame_8)
    self.formLayout.setObjectName(_fromUtf8("formLayout"))
    self.documentReaderLabel = QtGui.QLabel(self.frame_8)
    self.documentReaderLabel.setObjectName(_fromUtf8("documentReaderLabel"))
    self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.documentReaderLabel)
    self.documentReaderComboBox = QtGui.QComboBox(self.frame_8)
    self.documentReaderComboBox.setObjectName(_fromUtf8("documentReaderComboBox"))
    self.documentReaderComboBox.addItem(_fromUtf8(""))
    self.documentReaderComboBox.addItem(_fromUtf8(""))
    self.documentReaderComboBox.addItem(_fromUtf8(""))
    self.documentReaderComboBox.addItem(_fromUtf8(""))
    self.documentReaderComboBox.addItem(_fromUtf8(""))
    self.documentReaderComboBox.addItem(_fromUtf8(""))
    self.documentReaderComboBox.addItem(_fromUtf8(""))
    self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.documentReaderComboBox)
    self.musicPlayerLabel = QtGui.QLabel(self.frame_8)
    self.musicPlayerLabel.setObjectName(_fromUtf8("musicPlayerLabel"))
    self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.musicPlayerLabel)
    self.musicPlayerComboBox = QtGui.QComboBox(self.frame_8)
    self.musicPlayerComboBox.setObjectName(_fromUtf8("musicPlayerComboBox"))
    self.musicPlayerComboBox.addItem(_fromUtf8(""))
    self.musicPlayerComboBox.addItem(_fromUtf8(""))
    self.musicPlayerComboBox.addItem(_fromUtf8(""))
    self.musicPlayerComboBox.addItem(_fromUtf8(""))
    self.musicPlayerComboBox.addItem(_fromUtf8(""))
    self.musicPlayerComboBox.addItem(_fromUtf8(""))
    self.musicPlayerComboBox.addItem(_fromUtf8(""))
    self.musicPlayerComboBox.addItem(_fromUtf8(""))
    self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.musicPlayerComboBox)
    self.videoPlayerLabel = QtGui.QLabel(self.frame_8)
    self.videoPlayerLabel.setObjectName(_fromUtf8("videoPlayerLabel"))
    self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.videoPlayerLabel)
    self.videoPlayerComboBox = QtGui.QComboBox(self.frame_8)
    self.videoPlayerComboBox.setObjectName(_fromUtf8("videoPlayerComboBox"))
    self.videoPlayerComboBox.addItem(_fromUtf8(""))
    self.videoPlayerComboBox.addItem(_fromUtf8(""))
    self.videoPlayerComboBox.addItem(_fromUtf8(""))
    self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.videoPlayerComboBox)
    self.imageViewerLabel = QtGui.QLabel(self.frame_8)
    self.imageViewerLabel.setObjectName(_fromUtf8("imageViewerLabel"))
    self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.imageViewerLabel)
    self.imageViewerComboBox = QtGui.QComboBox(self.frame_8)
    self.imageViewerComboBox.setObjectName(_fromUtf8("imageViewerComboBox"))
    self.imageViewerComboBox.addItem(_fromUtf8(""))
    self.imageViewerComboBox.addItem(_fromUtf8(""))
    self.imageViewerComboBox.addItem(_fromUtf8(""))
    self.imageViewerComboBox.addItem(_fromUtf8(""))
    self.imageViewerComboBox.addItem(_fromUtf8(""))
    self.imageViewerComboBox.addItem(_fromUtf8(""))
    self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.imageViewerComboBox)
    self.gridLayout_15.addWidget(self.frame_8, 0, 0, 1, 1)
    self.contentWidget.addWidget(self.page_2)
    self.page_3 = QtGui.QWidget()
    self.page_3.setObjectName(_fromUtf8("page_3"))
    self.gridLayout_16 = QtGui.QGridLayout(self.page_3)
    self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
    self.frame_9 = QtGui.QFrame(self.page_3)
    self.frame_9.setObjectName(_fromUtf8("frame_9"))
    self.formLayout_3 = QtGui.QFormLayout(self.frame_9)
    self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
    self.textEditorLabel = QtGui.QLabel(self.frame_9)
    self.textEditorLabel.setObjectName(_fromUtf8("textEditorLabel"))
    self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.textEditorLabel)
    self.textEditorComboBox = QtGui.QComboBox(self.frame_9)
    self.textEditorComboBox.setObjectName(_fromUtf8("textEditorComboBox"))
    self.textEditorComboBox.addItem(_fromUtf8(""))
    self.textEditorComboBox.addItem(_fromUtf8(""))
    self.textEditorComboBox.addItem(_fromUtf8(""))
    self.textEditorComboBox.addItem(_fromUtf8(""))
    self.textEditorComboBox.addItem(_fromUtf8(""))
    self.textEditorComboBox.addItem(_fromUtf8(""))
    self.textEditorComboBox.addItem(_fromUtf8(""))
    self.textEditorComboBox.addItem(_fromUtf8(""))
    self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.textEditorComboBox)
    self.wordProcessorLabel = QtGui.QLabel(self.frame_9)
    self.wordProcessorLabel.setObjectName(_fromUtf8("wordProcessorLabel"))
    self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.wordProcessorLabel)
    self.wordProcessorComboBox = QtGui.QComboBox(self.frame_9)
    self.wordProcessorComboBox.setObjectName(_fromUtf8("wordProcessorComboBox"))
    self.wordProcessorComboBox.addItem(_fromUtf8(""))
    self.wordProcessorComboBox.addItem(_fromUtf8(""))
    self.wordProcessorComboBox.addItem(_fromUtf8(""))
    self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.wordProcessorComboBox)
    self.spreadsheetEditorLabel = QtGui.QLabel(self.frame_9)
    self.spreadsheetEditorLabel.setObjectName(_fromUtf8("spreadsheetEditorLabel"))
    self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.spreadsheetEditorLabel)
    self.spreadsheetEditorComboBox = QtGui.QComboBox(self.frame_9)
    self.spreadsheetEditorComboBox.setObjectName(_fromUtf8("spreadsheetEditorComboBox"))
    self.spreadsheetEditorComboBox.addItem(_fromUtf8(""))
    self.spreadsheetEditorComboBox.addItem(_fromUtf8(""))
    self.spreadsheetEditorComboBox.addItem(_fromUtf8(""))
    self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.spreadsheetEditorComboBox)
    self.gridLayout_16.addWidget(self.frame_9, 0, 0, 1, 1)
    self.contentWidget.addWidget(self.page_3)
    self.page_4 = QtGui.QWidget()
    self.page_4.setObjectName(_fromUtf8("page_4"))
    self.gridLayout_17 = QtGui.QGridLayout(self.page_4)
    self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
    self.frame_10 = QtGui.QFrame(self.page_4)
    self.frame_10.setObjectName(_fromUtf8("frame_10"))
    self.gridLayout_18 = QtGui.QGridLayout(self.frame_10)
    self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
    self.label_8 = QtGui.QLabel(self.frame_10)
    self.label_8.setObjectName(_fromUtf8("label_8"))
    self.gridLayout_18.addWidget(self.label_8, 0, 0, 1, 2)
    self.verticalLayout_4 = QtGui.QVBoxLayout()
    self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
    self.label_5 = QtGui.QLabel(self.frame_10)
    self.label_5.setAlignment(QtCore.Qt.AlignCenter)
    self.label_5.setObjectName(_fromUtf8("label_5"))
    self.verticalLayout_4.addWidget(self.label_5)
    self.plainTextEdit = QtGui.QPlainTextEdit(self.frame_10)
    font = QtGui.QFont()
    font.setFamily(_fromUtf8("Inconsolata"))
    font.setPointSize(11)
    self.plainTextEdit.setFont(font)
    self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
    self.verticalLayout_4.addWidget(self.plainTextEdit)
    self.gridLayout_18.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
    self.verticalLayout_3 = QtGui.QVBoxLayout()
    self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
    self.label_7 = QtGui.QLabel(self.frame_10)
    self.label_7.setAlignment(QtCore.Qt.AlignCenter)
    self.label_7.setObjectName(_fromUtf8("label_7"))
    self.verticalLayout_3.addWidget(self.label_7)
    self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.frame_10)
    font = QtGui.QFont()
    font.setFamily(_fromUtf8("Inconsolata"))
    font.setPointSize(11)
    self.plainTextEdit_2.setFont(font)
    self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
    self.verticalLayout_3.addWidget(self.plainTextEdit_2)
    self.gridLayout_18.addLayout(self.verticalLayout_3, 2, 1, 1, 1)
    spacerItem = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
    self.gridLayout_18.addItem(spacerItem, 1, 0, 1, 2)
    self.gridLayout_17.addWidget(self.frame_10, 0, 0, 1, 1)
    self.contentWidget.addWidget(self.page_4)
    self.gridLayout_2.addWidget(self.contentWidget, 1, 1, 1, 1)
    self.frame = QtGui.QFrame(self.centralwidget)
    self.frame.setObjectName(_fromUtf8("frame"))
    self.gridLayout = QtGui.QGridLayout(self.frame)
    self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
    self.horizontalLayout = QtGui.QHBoxLayout()
    self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
    self.cancelButton = QtGui.QPushButton(self.frame)
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.cancelButton.setIcon(icon)
    self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
    self.horizontalLayout.addWidget(self.cancelButton)
    spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.horizontalLayout.addItem(spacerItem1)
    self.backButton = QtGui.QPushButton(self.frame)
    self.backButton.setEnabled(False)
    self.backButton.setIcon(icon)
    self.backButton.setObjectName(_fromUtf8("backButton"))
    self.horizontalLayout.addWidget(self.backButton)
    self.forwardButton = QtGui.QPushButton(self.frame)
    self.forwardButton.setIcon(icon)
    self.forwardButton.setObjectName(_fromUtf8("forwardButton"))
    self.horizontalLayout.addWidget(self.forwardButton)
    self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
    self.gridLayout_2.addWidget(self.frame, 2, 0, 1, 2)
    MainWindow.setCentralWidget(self.centralwidget)

    self.retranslateUi(MainWindow)
    self.contentWidget.setCurrentIndex(0)
    self.documentReaderComboBox.setCurrentIndex(1)
    self.musicPlayerComboBox.setCurrentIndex(1)
    self.videoPlayerComboBox.setCurrentIndex(1)
    self.imageViewerComboBox.setCurrentIndex(1)
    self.textEditorComboBox.setCurrentIndex(1)
    self.wordProcessorComboBox.setCurrentIndex(1)
    self.spreadsheetEditorComboBox.setCurrentIndex(1)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

  def retranslateUi(self, MainWindow):
    MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Induction Linux Setup", None, QtGui.QApplication.UnicodeUTF8))
    self.label.setText(QtGui.QApplication.translate("MainWindow", "Header Text", None, QtGui.QApplication.UnicodeUTF8))
    self.progressList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Step", None, QtGui.QApplication.UnicodeUTF8))
    __sortingEnabled = self.progressList.isSortingEnabled()
    self.progressList.setSortingEnabled(False)
    self.progressList.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "Introduction", None, QtGui.QApplication.UnicodeUTF8))
    self.progressList.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "Disk Setup", None, QtGui.QApplication.UnicodeUTF8))
    self.progressList.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Install Destination", None, QtGui.QApplication.UnicodeUTF8))
    self.progressList.topLevelItem(1).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Swap Partition", None, QtGui.QApplication.UnicodeUTF8))
    self.progressList.topLevelItem(2).setText(0, QtGui.QApplication.translate("MainWindow", "User Accounts", None, QtGui.QApplication.UnicodeUTF8))
    self.progressList.topLevelItem(3).setText(0, QtGui.QApplication.translate("MainWindow", "Default Software", None, QtGui.QApplication.UnicodeUTF8))
    self.progressList.topLevelItem(3).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Web", None, QtGui.QApplication.UnicodeUTF8))
    self.progressList.topLevelItem(3).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Multimedia", None, QtGui.QApplication.UnicodeUTF8))
    self.progressList.topLevelItem(3).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "Development", None, QtGui.QApplication.UnicodeUTF8))
    self.progressList.topLevelItem(3).child(3).setText(0, QtGui.QApplication.translate("MainWindow", "Office", None, QtGui.QApplication.UnicodeUTF8))
    self.progressList.topLevelItem(4).setText(0, QtGui.QApplication.translate("MainWindow", "Installation", None, QtGui.QApplication.UnicodeUTF8))
    self.progressList.topLevelItem(5).setText(0, QtGui.QApplication.translate("MainWindow", "All Done", None, QtGui.QApplication.UnicodeUTF8))
    self.progressList.setSortingEnabled(__sortingEnabled)
    self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Welcome to the Induction Linux Setup guide.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">When you are ready to begin, click the &quot;<span style=\" font-weight:600;\">Start</span>&quot; button below.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
    self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This is the setup guide allow you to configure some basic system settings before the installation begins, including:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The user interface style.</li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The default web browser.</li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The default account\'s credentials.</li></ul>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Click &quot;<span style=\" font-weight:600;\">Forward</span>&quot; to begin the installation process.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
    self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Induction Linux needs a partition to install itself onto.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select one below:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
    self.partitionList.setSortingEnabled(True)
    self.partitionList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Label", None, QtGui.QApplication.UnicodeUTF8))
    self.partitionList.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
    self.partitionList.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
    self.partitionList.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Identifier", None, QtGui.QApplication.UnicodeUTF8))
    self.partitionList.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "UUID", None, QtGui.QApplication.UnicodeUTF8))
    self.label_6.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">It is recommended that you have a Swap partition. A Swap partition is used as if it were RAM, but not in every case. In case you don\'t have enough RAM to run the applications you need, Linux uses the Swap partition as RAM.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Note that Swap space is <span style=\" font-style:italic;\">not</span> as fast as normal RAM. It is much, much slower, but it gets the job done.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
    self.swapList.setSortingEnabled(True)
    self.swapList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Label", None, QtGui.QApplication.UnicodeUTF8))
    self.swapList.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
    self.swapList.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
    self.swapList.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Identifier", None, QtGui.QApplication.UnicodeUTF8))
    self.swapList.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "UUID", None, QtGui.QApplication.UnicodeUTF8))
    self.diskSpaceWarning.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Induction Linux needs at least <span style=\" font-weight:600;\">2.5GB</span> of disk space to function properly.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The partition that you have selected currently has a size of <span style=\" font-weight:600;\">{{disk_space}}</span>, which leaves you with a total of <span style=\" font-weight:600;\">{{useable_space}}</span> for personal files and additional software.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Are you sure that you want to continue with the installation? If you\'d like to change the install partition, press the &quot;<span style=\" font-weight:600;\">Back</span>&quot; button until you reach the installation destination step.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
    self.diskSpaceWarning_2.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'DejaVu LGC Sans\';\">You can configure Induction\'s default applications here. If you are fine with the defaults, just click the </span><span style=\" font-family:\'DejaVu LGC Sans\'; font-weight:600;\">Skip</span><span style=\" font-family:\'DejaVu LGC Sans\';\"> button.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
    self.webBrowserLabel.setText(QtGui.QApplication.translate("MainWindow", "Web Browser", None, QtGui.QApplication.UnicodeUTF8))
    self.webBrowserComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Mozilla Firefox", None, QtGui.QApplication.UnicodeUTF8))
    self.webBrowserComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Mozilla Nightly", None, QtGui.QApplication.UnicodeUTF8))
    self.webBrowserComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Opera", None, QtGui.QApplication.UnicodeUTF8))
    self.webBrowserComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Google Chrome (stable)", None, QtGui.QApplication.UnicodeUTF8))
    self.webBrowserComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Google Chrome (beta)", None, QtGui.QApplication.UnicodeUTF8))
    self.webBrowserComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Google Chrome (dev)", None, QtGui.QApplication.UnicodeUTF8))
    self.webBrowserComboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "Chromium (stable)", None, QtGui.QApplication.UnicodeUTF8))
    self.webBrowserComboBox.setItemText(7, QtGui.QApplication.translate("MainWindow", "Chromium (beta)", None, QtGui.QApplication.UnicodeUTF8))
    self.webBrowserComboBox.setItemText(8, QtGui.QApplication.translate("MainWindow", "Chromium (dev)", None, QtGui.QApplication.UnicodeUTF8))
    self.webBrowserComboBox.setItemText(9, QtGui.QApplication.translate("MainWindow", "Midori", None, QtGui.QApplication.UnicodeUTF8))
    self.webBrowserComboBox.setItemText(10, QtGui.QApplication.translate("MainWindow", "Jumanji", None, QtGui.QApplication.UnicodeUTF8))
    self.webBrowserComboBox.setItemText(11, QtGui.QApplication.translate("MainWindow", "Links", None, QtGui.QApplication.UnicodeUTF8))
    self.webBrowserComboBox.setItemText(12, QtGui.QApplication.translate("MainWindow", "Dillo", None, QtGui.QApplication.UnicodeUTF8))
    self.webBrowserComboBox.setItemText(13, QtGui.QApplication.translate("MainWindow", "Uzbl", None, QtGui.QApplication.UnicodeUTF8))
    self.mailClientLabel.setText(QtGui.QApplication.translate("MainWindow", "Mail Client", None, QtGui.QApplication.UnicodeUTF8))
    self.mailClientComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Mozilla Thunderbird", None, QtGui.QApplication.UnicodeUTF8))
    self.mailClientComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Mozilla Thunderbird (nightly)", None, QtGui.QApplication.UnicodeUTF8))
    self.mailClientComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Postler", None, QtGui.QApplication.UnicodeUTF8))
    self.mailClientComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Claws Mail", None, QtGui.QApplication.UnicodeUTF8))
    self.mailClientComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Sylpheed", None, QtGui.QApplication.UnicodeUTF8))
    self.bitTorrentClientLabel.setText(QtGui.QApplication.translate("MainWindow", "BitTorrent Client", None, QtGui.QApplication.UnicodeUTF8))
    self.bitTorrentClientComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Transmission", None, QtGui.QApplication.UnicodeUTF8))
    self.bitTorrentClientComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Deluge", None, QtGui.QApplication.UnicodeUTF8))
    self.bitTorrentClientComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "qBittorrent", None, QtGui.QApplication.UnicodeUTF8))
    self.bitTorrentClientComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "rTorrent", None, QtGui.QApplication.UnicodeUTF8))
    self.bitTorrentClientComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Vuze", None, QtGui.QApplication.UnicodeUTF8))
    self.chatClientLabel.setText(QtGui.QApplication.translate("MainWindow", "Chat Client", None, QtGui.QApplication.UnicodeUTF8))
    self.chatClientComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Pidgin", None, QtGui.QApplication.UnicodeUTF8))
    self.chatClientComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Gajim", None, QtGui.QApplication.UnicodeUTF8))
    self.chatClientComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "XChat", None, QtGui.QApplication.UnicodeUTF8))
    self.documentReaderLabel.setText(QtGui.QApplication.translate("MainWindow", "Document Reader", None, QtGui.QApplication.UnicodeUTF8))
    self.documentReaderComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "(none)", None, QtGui.QApplication.UnicodeUTF8))
    self.documentReaderComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Evince", None, QtGui.QApplication.UnicodeUTF8))
    self.documentReaderComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "ePDFView", None, QtGui.QApplication.UnicodeUTF8))
    self.documentReaderComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "llpp", None, QtGui.QApplication.UnicodeUTF8))
    self.documentReaderComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "zathura", None, QtGui.QApplication.UnicodeUTF8))
    self.documentReaderComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Xpdf", None, QtGui.QApplication.UnicodeUTF8))
    self.documentReaderComboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "MuPDF", None, QtGui.QApplication.UnicodeUTF8))
    self.musicPlayerLabel.setText(QtGui.QApplication.translate("MainWindow", "Music Player", None, QtGui.QApplication.UnicodeUTF8))
    self.musicPlayerComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "(none)", None, QtGui.QApplication.UnicodeUTF8))
    self.musicPlayerComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Banshee", None, QtGui.QApplication.UnicodeUTF8))
    self.musicPlayerComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Quod Libet", None, QtGui.QApplication.UnicodeUTF8))
    self.musicPlayerComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Amarok", None, QtGui.QApplication.UnicodeUTF8))
    self.musicPlayerComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Clementine", None, QtGui.QApplication.UnicodeUTF8))
    self.musicPlayerComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "DeaDBeeF", None, QtGui.QApplication.UnicodeUTF8))
    self.musicPlayerComboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "Exaile", None, QtGui.QApplication.UnicodeUTF8))
    self.musicPlayerComboBox.setItemText(7, QtGui.QApplication.translate("MainWindow", "Nightingale", None, QtGui.QApplication.UnicodeUTF8))
    self.videoPlayerLabel.setText(QtGui.QApplication.translate("MainWindow", "Video Player", None, QtGui.QApplication.UnicodeUTF8))
    self.videoPlayerComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "(none)", None, QtGui.QApplication.UnicodeUTF8))
    self.videoPlayerComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Parole", None, QtGui.QApplication.UnicodeUTF8))
    self.videoPlayerComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "VLC", None, QtGui.QApplication.UnicodeUTF8))
    self.imageViewerLabel.setText(QtGui.QApplication.translate("MainWindow", "Image Viewer", None, QtGui.QApplication.UnicodeUTF8))
    self.imageViewerComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "(none)", None, QtGui.QApplication.UnicodeUTF8))
    self.imageViewerComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Viewnior", None, QtGui.QApplication.UnicodeUTF8))
    self.imageViewerComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Feh", None, QtGui.QApplication.UnicodeUTF8))
    self.imageViewerComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "GpicView", None, QtGui.QApplication.UnicodeUTF8))
    self.imageViewerComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Ristretto", None, QtGui.QApplication.UnicodeUTF8))
    self.imageViewerComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Eye of GNOME", None, QtGui.QApplication.UnicodeUTF8))
    self.textEditorLabel.setText(QtGui.QApplication.translate("MainWindow", "Text Editor", None, QtGui.QApplication.UnicodeUTF8))
    self.textEditorComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "(none)", None, QtGui.QApplication.UnicodeUTF8))
    self.textEditorComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Geany", None, QtGui.QApplication.UnicodeUTF8))
    self.textEditorComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Leafpad", None, QtGui.QApplication.UnicodeUTF8))
    self.textEditorComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Gedit", None, QtGui.QApplication.UnicodeUTF8))
    self.textEditorComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Bluefish", None, QtGui.QApplication.UnicodeUTF8))
    self.textEditorComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Beaver", None, QtGui.QApplication.UnicodeUTF8))
    self.textEditorComboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "SciTE", None, QtGui.QApplication.UnicodeUTF8))
    self.textEditorComboBox.setItemText(7, QtGui.QApplication.translate("MainWindow", "cssed", None, QtGui.QApplication.UnicodeUTF8))
    self.wordProcessorLabel.setText(QtGui.QApplication.translate("MainWindow", "Word Processor", None, QtGui.QApplication.UnicodeUTF8))
    self.wordProcessorComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "(none)", None, QtGui.QApplication.UnicodeUTF8))
    self.wordProcessorComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Abiword", None, QtGui.QApplication.UnicodeUTF8))
    self.wordProcessorComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "LibreOffice Writer", None, QtGui.QApplication.UnicodeUTF8))
    self.spreadsheetEditorLabel.setText(QtGui.QApplication.translate("MainWindow", "Spreadsheet Editor", None, QtGui.QApplication.UnicodeUTF8))
    self.spreadsheetEditorComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "(none)", None, QtGui.QApplication.UnicodeUTF8))
    self.spreadsheetEditorComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Gnumeric", None, QtGui.QApplication.UnicodeUTF8))
    self.spreadsheetEditorComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "LibreOffice Calc", None, QtGui.QApplication.UnicodeUTF8))
    self.label_8.setText(QtGui.QApplication.translate("MainWindow", "If you would like to install any additional packages through this installer, feel free to add them below. One package per line.", None, QtGui.QApplication.UnicodeUTF8))
    self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Official Packages", None, QtGui.QApplication.UnicodeUTF8))
    self.label_7.setText(QtGui.QApplication.translate("MainWindow", "AUR Packages", None, QtGui.QApplication.UnicodeUTF8))
    self.cancelButton.setText(QtGui.QApplication.translate("MainWindow", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))
    self.backButton.setText(QtGui.QApplication.translate("MainWindow", "&Back", None, QtGui.QApplication.UnicodeUTF8))
    self.forwardButton.setText(QtGui.QApplication.translate("MainWindow", "&Start", None, QtGui.QApplication.UnicodeUTF8))

from QInstallProgress import QInstallProgress
import resources_rc
